version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elec_load
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: elec_load_app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/elec_load
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: