"""add unique board name per project

Revision ID: 423db4b91f5f
Revises: 4abde2fdbf24
Create Date: 2026-04-21 22:46:01.435878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423db4b91f5f'
down_revision: Union[str, Sequence[str], None] = '4abde2fdbf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_board_name', 'board', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_board_name', 'board', type_='unique')
    # ### end Alembic commands ###
