"""add composite unique constraint owner_id + name to project

Revision ID: 4abde2fdbf24
Revises: 6305152cbb58
Create Date: 2026-04-19 15:43:56.021330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abde2fdbf24'
down_revision: Union[str, Sequence[str], None] = '6305152cbb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_name', 'project', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_name', 'project', type_='unique')
    # ### end Alembic commands ###
