"""init models

Revision ID: 6305152cbb58
Revises: 
Create Date: 2026-04-16 22:23:51.178795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6305152cbb58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('simultaneity_factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_parent_id'), 'board', ['parent_id'], unique=False)
    op.create_index(op.f('ix_board_project_id'), 'board', ['project_id'], unique=False)
    op.create_table('consumer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_power_kw', sa.Float(), nullable=False),
    sa.Column('simultaneity_factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_board_id'), 'consumer', ['board_id'], unique=False)
    # ### end Alembic commands ###

    # Manual constraints
    op.create_index(
        "unique_root_per_project",
        "board",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL")
    )

    op.create_check_constraint(
        "check_simultaneity_factor_board",
        "board",
        "simultaneity_factor >= 0 AND simultaneity_factor <= 1"
    )

    op.create_check_constraint(
        "check_simultaneity_factor_consumer",
        "consumer",
        "simultaneity_factor >= 0 AND simultaneity_factor <= 1"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added
    op.drop_constraint("check_simultaneity_factor_consumer", "consumer", type_="check")
    op.drop_constraint("check_simultaneity_factor_board", "board", type_="check")
    op.drop_index("unique_root_per_project", table_name="board")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumer_board_id'), table_name='consumer')
    op.drop_table('consumer')
    op.drop_index(op.f('ix_board_project_id'), table_name='board')
    op.drop_index(op.f('ix_board_parent_id'), table_name='board')
    op.drop_table('board')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
