"""init models

Revision ID: 81e479145d88
Revises: 
Create Date: 2026-04-26 20:39:11.212458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e479145d88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_project_name')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('simultaneity_factor', sa.Float(), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(is_root = TRUE AND parent_id IS NULL) OR (is_root = FALSE)', name='check_root_board_consistency'),
    sa.CheckConstraint('simultaneity_factor >= 0 AND simultaneity_factor <= 1', name='check_simultaneity_factor_board'),
    sa.ForeignKeyConstraint(['parent_id'], ['boards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_board_name')
    )
    op.create_index(op.f('ix_boards_name'), 'boards', ['name'], unique=False)
    op.create_index(op.f('ix_boards_parent_id'), 'boards', ['parent_id'], unique=False)
    op.create_index(op.f('ix_boards_project_id'), 'boards', ['project_id'], unique=False)
    op.create_table('consumers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_power_kw', sa.Float(), nullable=False),
    sa.Column('simultaneity_factor', sa.Float(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='check_quantity_positive'),
    sa.CheckConstraint('simultaneity_factor >= 0 AND simultaneity_factor <= 1', name='check_simultaneity_factor_consumer'),
    sa.CheckConstraint('unit_power_kw >= 0', name='check_power_positive'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumers_board_id'), 'consumers', ['board_id'], unique=False)
    # ### end Alembic commands ###

    #Manually added
    op.create_index(
        "unique_root_per_project",
        "boards",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("is_root = true")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumers_board_id'), table_name='consumers')
    op.drop_table('consumers')
    op.drop_index(op.f('ix_boards_project_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_parent_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_name'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    #Manually added
    op.drop_index("unique_root_per_project", table_name="boards")
